### ISSUE TITLE
Cameras update

### ISSUE THREAD

**Issue by ichristen** [slmsuite/slmsuite#57]
Dashboard for the camera-related updates planned.

New interfaces:

- [x] #17 (polish/debugging) #80 , 
- (Later) #20 ,
- [x] #21 (polish/debugging), 
- [x] #25 , #67
- (Decided against) #51 ,
- (Decided against) #56 ,
- [x] #66 ,
- [x] #71 ,
- [x] #72 ,
- [x] #74 ,
- [x] `cv2` webcam interface #80 ,
- [x] Dark current and readout noise in simulated cameras #52 #69 .

Polished abstract functionality:

- (Later) #33 (though this could maybe be split into a separate update),
- [x] #55 ,
- [x] Multi-exposure high dynamic range imaging,
- [x] Revamp to how `get_image()` works with new interfaces: instead new cameras will write `_get_image_hw()` (in the same manner as `write()`  and `_write_hw()` for SLMs),
- (Later) Polishing the `trigger` and `grab` formalism in `get_image()` and forcing this functionality to be abstract.

Potentially:

- [x] Live ~~pyglet (alongside #7 )~~ ipywidget viewer of the camera,
- (Later) More careful pipelining of the data to GPU.

**Comment by coldkevin1991** [comment]
Hi ichristen,

I have several MindVision cameras, but it is difficult for me. If you have any interest in this camera, please try to develop it.
Thank you very much.

SDK: https://www.mindvision.com.cn/category/software/
[python_demo.zip](https://github.com/user-attachments/files/16191677/python_demo.zip)

**Comment by ichristen** [comment]
Thanks @coldkevin1991 for your suggestion! I opened up #71.
